### ISSUE TITLE
问题介绍

### ISSUE THREAD

**Issue by root00r** [netcan/NetcanOS#1]
1.在进入kernel.c的主函数之后，申请1M栈空间，这时候会报错，希望能修改下代码，我在boot/switch_to_pm.asm文件中改了下栈指针大小之后，测试可以成功申请大于1M的栈空间
改动之前代码：
mov ebp, 0x90000 ; 栈指针
改动之后代码：
mov ebp, 0x900000 ; 栈指针

**Comment by netcan** [comment]
具体测试环境？似乎默认栈空间没有那么大
